-- CreateTable
CREATE TABLE "Category" (
    "ID_CAT" SERIAL NOT NULL,
    "NAME" TEXT,
    "DESCRIPTION" TEXT,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("ID_CAT")
);

-- CreateTable
CREATE TABLE "Product" (
    "ID_PRODUCT" SERIAL NOT NULL,
    "ID_CAT" INTEGER,
    "NAME" TEXT,
    "DESCRIPTION" TEXT,
    "PRICE" TEXT,
    "DATE_DESCRIPTION" TEXT,
    "DATE_UPDATE" TEXT,
    "SERVICE" BOOLEAN,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("ID_PRODUCT")
);

-- CreateTable
CREATE TABLE "Service" (
    "ID_SERVICE" SERIAL NOT NULL,
    "ID_PRODUCT" INTEGER,
    "DATE_START" TIMESTAMP(3),
    "DATE_END" TIMESTAMP(3),

    CONSTRAINT "Service_pkey" PRIMARY KEY ("ID_SERVICE")
);

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_ID_CAT_fkey" FOREIGN KEY ("ID_CAT") REFERENCES "Category"("ID_CAT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Service" ADD CONSTRAINT "Service_ID_PRODUCT_fkey" FOREIGN KEY ("ID_PRODUCT") REFERENCES "Product"("ID_PRODUCT") ON DELETE SET NULL ON UPDATE CASCADE;
